### ISSUE TITLE
Example shows use of UrlParser.format; does not exist in 2.0?

### ISSUE THREAD

**Issue by inactivist** [evancz/url-parser#15]
Found this while porting some code from Elm 0.17 to 0.18.

README.md and [examples/App.elm](https://github.com/evancz/url-parser/blob/2.0.0/examples/App.elm#L53) reference  `UrlParser.format` function, though it appears to have been removed in the 2.0 release.

```
type DesiredPage = Blog Int | Search String

desiredPage : Parser (DesiredPage -> a) a
desiredPage =
  oneOf
    [ format Blog (s "blog" </> int)
    , format Search (s "search" </> string)
    ]
```

**Comment by sporto** [comment]
This is now called `map`

**Comment by prikhi** [comment]
Working on getting the example & readme up to date, will submit PR today.

**Comment by inactivist** [comment]
Thanks, I hoped to submit a PR to fix it but probably won't get to it for a few days at least.

**Comment by prikhi** [comment]
PR submitted, not sure if my solution is the golden path, it's just what I did for my app. Feedback welcome.

**Comment by evancz** [comment]
The README and examples are now updated. Sorry for the confusion!

**Comment by inactivist** [comment]
Thanks for the quick turnaround.  I'll try "pitch in" somewhere around here...

**Comment by evancz** [comment]
Don't feel pressure to contribute through code! I think it's a weird pathology in programming communities that folks think "it doesn't count" if there's not something merged into master.

Opening a high-quality issue like this (where you explain how the problem appeared in practice, provide nice links to mistakes, and give a clear summary in the issue itself) is a great kind of contribution. Creating nice issues is a skill that very few people have (based on my observations) and this one is particularly well done!

In any case, I talk about this more in [Code is the Easy Part](https://www.youtube.com/watch?v=DSjbTC-hvqQ) because I think there are lots of folks who make great contributions, but this ambient culture around PRs hide this and encourage less efficient collaboration. Point is, thanks for reporting this :)

**Comment by inactivist** [comment]
> Don't feel pressure to contribute through code! I think it's a weird pathology in programming communities that folks think "it doesn't count" if there's not something merged into master.

@evancz -- Thanks for the kind words. I don't feel that way at all, FWIW.  Cheers!
