### ISSUE TITLE
'Problem in dependency evancz/url-parser 2.0.1'

### ISSUE THREAD

**Issue by Socratic1** [evancz/url-parser#29]
Hey there, 

I've used url-parser in previous projects with no problem; however, I recently installed url-parser into a new project, and received this error. 

> 
> Problem in dependency evancz/url-parser 2.0.1
> 
> The elm-package.json constraints of 'evancz/url-parser' are probably
> letting too much stuff through. Definitely open an issue on the relevant github
> repo to get this fixed and save other people from this pain.

(process-bot wants me to let you know: 
I'm using elm 0.18.0,
I'm working with OS X El Capitan and Chrome Version 55.0.2883.95 (64-bit), though I have no idea why that would affect anything)

I'm not exactly sure what 'letting too much stuff through' means, maybe that the interface reveals unnecessary/interruptive functions. Anyway, I thought I ought to let you guys know!

**Comment by evancz** [comment]
I wonder if this is because multiple packages expose a `</>` or `<?>` operator.

Without knowing more about your `elm-package.json`, I don't know how I can give more hints about what might be going wrong though. Thanks for the report, and my sense is that it is a relatively specialty issue you are running into that is not inherently related to this package.
