### ISSUE TITLE
Support optional parts in URL

### ISSUE THREAD

**Issue by zdychacek** [evancz/url-parser#7]
Hi,

I want to ask if there is a plan to support optional parts in URL?

ex.

Create a parser:

```
type Page =
    ItemsList (Maybe Int)

parser = format ItemsList (s "/items" </> (maybe int))
```

Parse "list item detail" URL:

`UrlParser.parse identity parser "/items/1"` -> `Ok (ItemsList (Just 1))`

Parse "list" URL:

`UrlParser.parse identity parser "/items"` -> `Ok (ItemsList Nothing)`

Thanks for your response.

O.

**Comment by evancz** [comment]
I'd say we are in a listen-and-learn phase. This seems like a pretty common use-case, so I'd expect to support it longer term. For now, I'd want more data though. There may be some other URL parsers out there that have more features at the moment, and I'd recommend giving them a shot. Ideally the community will produce something really nice that covers everything!

**Comment by evancz** [comment]
I recommend you do this scenario like this:

``` elm
type Page =
    ItemsList (Maybe Int)

parser =
  oneOf
    [ format (ItemsList << Just) (s "items" </> int)
    , format (ItemsList Nothing) (s "items")
    ]
```

You will be able to define `maybe` in the next version of this library with the addition of `top`. That said, I don't want to add this into the core library without more experience reports. My gut says that having `maybe` will let people write more frail code because `items/42/info` may make sense but `items/info` may not. I think `maybe` makes it easier to end up with this mistake.
